modLoader = "javafml"
loaderVersion = "[4,)"
license = "GPL-3.0-only"

[[mods]]
modId = "bydalc"
version = "1.0.0"
displayName = "通透了"
authors = "Xyu_Fox"
description = '''
Adds a music disc. While it plays, every creature within 10 blocks - including bosses and players - wobbles and stretches like jelly and spins around 360 degrees, without moving the camera.
'''

[[mixins]]
config = "bydalc.mixins.json"

[[dependencies.bydalc]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.77,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bydalc]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"